//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18047
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSNovelCrawler.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSNovelCrawler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 請設定預設下載資料夾： 的當地語系化字串。
        /// </summary>
        internal static string FormConfig_button1_Click_ {
            get {
                return ResourceManager.GetString("FormConfig_button1_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇你的下載資料夾 的當地語系化字串。
        /// </summary>
        internal static string FormMain_BtnBrowseDir_Click_選擇你的下載資料夾 {
            get {
                return ResourceManager.GetString("FormMain_BtnBrowseDir_Click_選擇你的下載資料夾", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否刪除選取的任務？ 的當地語系化字串。
        /// </summary>
        internal static string FormMain_toolStripDel_Click_ {
            get {
                return ResourceManager.GetString("FormMain_toolStripDel_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除任務 的當地語系化字串。
        /// </summary>
        internal static string FormMain_toolStripDel_Click_刪除任務 {
            get {
                return ResourceManager.GetString("FormMain_toolStripDel_Click_刪除任務", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停止下載 的當地語系化字串。
        /// </summary>
        internal static string FormMain_toolStripStop_Click_停止下載 {
            get {
                return ResourceManager.GetString("FormMain_toolStripStop_Click_停止下載", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否停止選取的下載? 的當地語系化字串。
        /// </summary>
        internal static string FormMain_toolStripStop_Click_是否停止選取的下載_ {
            get {
                return ResourceManager.GetString("FormMain_toolStripStop_Click_是否停止選取的下載_", resourceCulture);
            }
        }
    }
}
